FROM registry.access.redhat.com/ubi8/ubi
WORKDIR /work/

RUN yum install wget -y

RUN wget https://github.com/puzzle/amm-techlab/releases/download/1.0.0/application

RUN chmod -R 775 /work
EXPOSE 8080
CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]
