## Stage 1 : build with maven builder image with native capabilities
FROM docker.io/schlapzz/producer-base:0.1.1

RUN mvn -f /usr/src/app/pom.xml clean package


COPY /usr/src/app/target/lib/* /deployments/lib/
COPY /usr/src/app/target/*-runner.jar /deployments/app.jar

EXPOSE 8080
USER 1001

ENTRYPOINT [ "/deployments/run-java.sh" ]