apiVersion: v1
kind: List
metadata:
  labels:
    application: quarkus-techlab
items:

  - apiVersion: v1
    kind: ImageStream
    metadata:
      labels:
        application: quarkus-techlab
      name: data-producer
    spec:
      lookupPolicy:
        local: false
      tags:
        - annotations:
            openshift.io/imported-from: g1raffi/quarkus-techlab-data-producer:kafka
          from:
            kind: DockerImage
            name: g1raffi/quarkus-techlab-data-producer:kafka
          name: kafka
          referencePolicy:
            type: Source

  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        application: quarkus-techlab
      name: data-producer
    spec:
      replicas: 1
      selector:
        deploymentConfig: data-producer
      strategy:
        type: Recreate
      template:
        metadata:
          labels:
            application: quarkus-techlab
            deploymentConfig: data-producer
        spec:
          containers:
            - image: g1raffi/data-producer:kafka
              imagePullPolicy: Always
              livenessProbe:
                failureThreshold: 5
                httpGet:
                  path: /health
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 3
                periodSeconds: 20
                successThreshhold: 1
                timeoutSeconds: 15
              readinessProbe:
                failureThreshold: 5
                httpGet:
                  path: /health
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 3
                periodSeconds: 20
                successThreshold: 1
                timeoutSeconds: 15
              name: data-producer
              port:
                - containerPort: 8080
                  name: http
                  protocol: TCP
              resources:
                limits:
                  cpu: 1
                  memory: 500Mi
                requests:
                  cpu: 50m
                  memory: 100Mi
      triggers:
        - type: ConfigChange
        - imageChangeParams:
            automatic: true
            containerNames:
              - data-producer
            from:
              kind: ImageStreamTag
              name: data-producer:kafka
          type: ImageChange

  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        application: quarkus-techlab
      name: data-producer
    spec:
      ports:
        - name: data-producer-http
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        deploymentConfig: data-producer
      sessionAffinity: None
      type: ClusterIP

  - apiVersion: v1
    kind: Route
    metadata:
      labels:
        application: quarkus-techlab
      name: data-producer
    spec:
      path: /
      tls:
        caCertificate: null
        certificate: null
        insecureEdgeTerminationPolicy: Allow
        key: null
        termination: edge
      to:
        kind: Service
        name: data-producer
