apiVersion: v1
kind: List
metadata:
  labels:
    application: quarkus-techlab
items:
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      name: data-producer
    spec:
      lookupPolicy:
        local: false
      tags:
      - annotations: null
        from:
          kind: DockerImage
          name: g1raffi/quarkus-techlab-data-producer:rest
        generation: 1
        importPolicy:
          scheduled: true
        name: rest
        referencePolicy:
        type: Source
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        application: quarkus-techlab
      name: data-consumer
    spec:
      replicas: 1
      selector:
        matchLabels:
          deployment: data-consumer
      template:
        metadata:
          labels:
            application: quarkus-techlab
            deployment: data-consumer
        spec:
          containers:
            - image: g1raffi/quarkus-techlab-data-consumer:rest
              imagePullPolicy: Always
              livenessProbe:
                failureThreshold: 5
                httpGet:
                  path: /health
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 3
                periodSeconds: 20
                successThreshhold: 1
                timeoutSeconds: 15
              readinessProbe:
                failureThreshold: 5
                httpGet:
                  path: /health
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 3
                periodSeconds: 20
                successThreshold: 1
                timeoutSeconds: 15
              name: data-consumer
              port:
                - containerPort: 8080
                  name: http
                  protocol: TCP
              resources:
                limits:
                  cpu: 1
                  memory: 500Mi
                requests:
                  cpu: 50m
                  memory: 100Mi

  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        application: quarkus-techlab
      name: data-consumer
    spec:
      ports:
        - name: data-consumer-http
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        deployment: data-consumer
      sessionAffinity: None
      type: ClusterIP

  - apiVersion: v1
    kind: Route
    metadata:
      labels:
        application: quarkus-techlab
      name: data-consumer
    spec:
      path: /
      tls:
        caCertificate: null
        certificate: null
        insecureEdgeTerminationPolicy: Allow
        key: null
        termination: edge
      to:
        kind: Service
        name: data-consumer
